### ISSUE TITLE
Installation takes near infinite time.

### ISSUE THREAD

**Issue by vishnumaiea** [refkotay/quick-scroll#2] opened 2017-05-15 09:05 UTC
Problem is the title.

**Comment by refkotay** [comment] 2017-05-17 17:35
Unfortunately I can't reproduce this. Can you provide atom version and OS?

Did you check if other packages take as long?
Preferably after that, did you try an uninstall and reinstall to reproduce the problem?

Does it take minutes? Hours?

**Comment by Extarys** [comment] 2017-05-17 19:08
Under Linux Mint with Atom I didn't experience this issue (BTW thanks for the plugin!!)

**Comment by vishnumaiea** [comment] 2017-05-18 05:58
Sorry I didn't add the OS details before.

I'm running it on Windows 7 Ultimate SP1 64-bit and Atom version is 1.17.0 x64.

It took about 5-6 minutes to install, I'm not sure becasue I closed the Settings window before it completes installation. But when I later checked, the installation had finished and I could use it.  I tried installing some other extensions and they also took some minutes.

The Atom is already slow on Windows may be that's why (or I was impatient !)

You may close this issue. :)

**Comment by vishnumaiea** [comment] 2017-05-18 06:01
Thanks for the plugin BTW. It's really helpful.

**Comment by refkotay** [comment] 2017-05-18 17:47
Glad to hear the plugin is useful to you guys : )

There was [a similar problem](https://discuss.atom.io/t/why-is-apm-so-ridiculously-slow-for-me/12035) on atom's discuss forum but it seems it was resolved by an apm/node update some time ago. All I can suggest is to leave an issue on the [apm repository](https://github.com/atom/apm). I don't see any similar issues there.

I will go ahead and close as I think it's apm related, but I hope you find a solution.

**Closed by refkotay** 2017-05-18 17:47 UTC
Labels: needs reproduction
